apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: devpod
  name: nodepolicyprofile-devpod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      devpod: nodepolicyprofile-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        devpod: nodepolicyprofile-controller
        app.kubernetes.io/instance: nodepolicyprofile
        app.kubernetes.io/name: k8s-policy-controller
    spec:
      containers:
        - image: golang:1.14-buster
          imagePullPolicy: Always
          name: dev
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /root
              name: workspace
              readOnly: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: nodepolicyprofile-controller-tls
        - name: workspace
          persistentVolumeClaim:
            claimName: devpod-workspace
      dnsPolicy: ClusterFirst
      serviceAccountName: nodepolicyprofile-controller
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
