---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "node-policy-webhook.fullname" . }}
  labels:
    {{- include "node-policy-webhook.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "node-policy-webhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    objectSelector:
      matchExpressions:
        - key: app
          operator: NotIn
          values: ["node-policy-webhook"]
    clientConfig:
      caBundle: {{ .Values.caBundle }}
      service:
        name: {{ include "node-policy-webhook.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: {{ .Values.webhook.sideEffects }}
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    reinvocationPolicy: {{ .Values.webhook.reinvocationPolicy }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    admissionReviewVersions:
    {{- range .Values.webhook.admissionReviewVersions }}
    - {{ . | quote }}
    {{- end }}
