apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-policy-webhook.serviceAccountName" . }}
  labels:
    {{- include "node-policy-webhook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
