# This is a basic workflow to help you get started with Actions

name: Helm Chart

on:
  push:
    branches:
      - master
    paths:
      - 'chart/*'

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: goodsmileduck/helm-push-action@v3
      env:
        SOURCE_DIR: 'chart'
        CHART_FOLDER: 'node-policy-webhook'
        CHARTMUSEUM_URL: 'https://charts.softonic.io'
        CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
        CHARTMUSEUM_PASSWORD: '${{ secrets.CHARTMUSEUM_PASSWORD }}'
